import Head from "next/head";
import { Inter } from "@next/font/google";
import NavbarsHead from "@/components/navbars/NavbarsHead";
import Hero from "@/components/heroes/Hero";
import GuestStar from "@/components/guestStar/GuestStar";
import Rondown from "@/components/rundown/Rondown";
import CardTiket from "@/components/cards_tiket/CardTiket";
import Pilar from "@/components/pillar/Pillar";
const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>PT Wibu Sukses Bersama Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavbarsHead />
      <Hero />
      <GuestStar />
      <Rondown />
      <CardTiket />
      <Pilar />
    </>
  );
}
