import Head from "next/head";
import { Inter } from "@next/font/google";
import NavbarsHead from "@/components/navbars/NavbarsHead";
import Hero from "@/components/heroes/Hero";
import GuestStar from "@/components/guestStar/GuestStar";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>PT Wibu Sukses Bersama Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavbarsHead />
      <Hero />
      <GuestStar />
    </>
  );
}
